import '../scss/Globales.scss'
import '../scss/Calendar.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Providers } from './providers'
import { Box } from '@chakra-ui/react';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Beyond Valencia',
  description: 'Generated by create next app',
  icons: {
    icon: "/icon.svg",
    apple: "icon.svg"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box className={poppins.className}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}
